import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import sanity from "../lib/sanity/client";
import { commissionFormQuery } from "../lib/sanity/queries";
import CartSummary from "../components/CartSummary";
import { formatCurrencyString, useShoppingCart } from "use-shopping-cart";

const Home: NextPage = ({ form }) => {
  console.log(form);
  const { addItem, removeItem } = useShoppingCart();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>
          {formatCurrencyString({
            value: 2000,
            currency: "usd",
          })}
        </p>
        <button onClick={() => addItem(product)}>Add to cart</button>
        <button onClick={() => removeItem(product.id)}>Remove</button>
      </main>
      <CartSummary />

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export const getStaticProps = async () => {
  const form = await sanity.fetch(commissionFormQuery);

  return {
    props: { form },
  };
};

export default Home;
